version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selfcare
    ports:
      - 5432:5432

  website:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@database:5432/selfcare
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules/
    ports:
      - 3000:3000
    depends_on:
      - database
    tty: true
